version: '3.8'

services:
  backend:
    build: .
    container_name: cloud-storage-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - cloud-storage-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloud-storage-frontend
    ports:
      - "80:80"
    networks:
      - cloud-storage-network
    depends_on:
      - backend

networks:
  cloud-storage-network:
    driver: bridge